### ISSUE TITLE
话说该项目是还没完善吗？

### ISSUE THREAD

**Issue by railwcode** [zhangsean/heroku-xray#1]
我这边部署上去貌似连接不上

**Comment by zhangsean** [comment]
很遗憾，XTLS这种部署方式需要在xray本体配置证书，但是heroku和cloudflare都是自带证书，不开放80端口的。搞了很久也没有成功。
你试试，如果成功了，可以分享一下。
&nbsp;

信心+开心=顺心


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月30日(星期三) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [zhangsean/heroku-xray] 话说该项目是还没完善吗？ (#1)





 
我这边部署上去貌似连接不上

**Comment by railwcode** [comment]
> 很遗憾，XTLS这种部署方式需要在xray本体配置证书，但是heroku和cloudflare都是自带证书，不开放80端口的。搞了很久也没有成功。 你试试，如果成功了，可以分享一下。 &nbsp; 信心+开心=顺心 &nbsp;
> […](#)

soga
